services:
  opportunity-markets:
    container_name: opportunity-markets
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SAPPHIRE_RPC: ${NEXT_PUBLIC_SAPPHIRE_RPC}
        NEXT_PUBLIC_SAPPHIRE_MAINNET_RPC: ${NEXT_PUBLIC_SAPPHIRE_MAINNET_RPC}
        NEXT_PUBLIC_FACTORY_ADDRESS: ${NEXT_PUBLIC_FACTORY_ADDRESS}
        NEXT_PUBLIC_COLLATERAL_TOKEN: ${NEXT_PUBLIC_COLLATERAL_TOKEN}
        NEXT_PUBLIC_DEMO_MODE: ${NEXT_PUBLIC_DEMO_MODE}
        NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID}
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_SAPPHIRE_RPC=${NEXT_PUBLIC_SAPPHIRE_RPC}
      - NEXT_PUBLIC_SAPPHIRE_MAINNET_RPC=${NEXT_PUBLIC_SAPPHIRE_MAINNET_RPC}
      - NEXT_PUBLIC_FACTORY_ADDRESS=${NEXT_PUBLIC_FACTORY_ADDRESS}
      - NEXT_PUBLIC_COLLATERAL_TOKEN=${NEXT_PUBLIC_COLLATERAL_TOKEN}
      - NEXT_PUBLIC_DEMO_MODE=${NEXT_PUBLIC_DEMO_MODE}
      - NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID}
    ports:
      - 3000:3000
    restart: unless-stopped
